[package]
name = "collision_detector"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "collision_detector"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.2"
nalgebra = "0.20"
ncollide3d = "0.22"
kiss3d = "0.32"
rand = "0.8.0"
